version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: react-login-form
    path: ""
    text-resources:
      - path: public/locales/*/translation.json
        format: flat-key-value
